modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GPLv3"
issueTrackerURL="https://github.com/TyrellPlayz/AdvancedTech/issues" #optional

[[mods]] #mandatory
modId="advanced_tech" #mandatory
version="${mod_version}" #mandatory
displayName="Advanced Technology" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="logo.png" #optional
authors="TyrellPlayz" #optional
description='''
Lots of advanced technology.
'''
[[dependencies.advanced_tech]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.advanced_tech]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.advanced_tech]]
    modId="zlib"
    mandatory=true
    versionRange="[${zlib_version},)"
    ordering="NONE"
    side="BOTH"
